name: CD - Deploy to Minikube using Github Actions

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the master/main branch or on pull request
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build job
  job1:
    name: Build and Deploy to Minikube
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    # Job's steps
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t local/cicd-example .
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy.yaml
          kubectl wait --for=condition=Ready pod -l app=cicd-example
          kubectl get all
      - name: Test service URLs
        run: |
          echo "CLUSTER_IP=$(kubectl get service cicd-example --output='jsonpath={.spec.clusterIPs[0]}')"
          echo "SERVICE_URL=$(minikube service cicd-example --url)"
          kubectl port-forward service/cicd-example 8080:8080 &> /dev/null &
          sleep 5
          kubectl port-forward service/cicd-example 8080:8080 &> /dev/null &
      - run: |
          curl -i http://localhost:8080/
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete