name: CI
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the master/main branch
  push:
    branches: [ main ]

jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    #Job's steps
    steps:
      #Check-out your repository under
      - uses: actions/checkout@v4
      #Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      #Run Tests
      - name: Run Tests
        run: mvn -B test
      # Report Coverage
      - name: Coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
            paths: |
              ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Store HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: | 
            ${{ github.workspace }}/**/target/site/jacoco/index.html,
            ${{ github.workspace }}/**/target/site/jacoco/jacoco-sessions.html

