name: CI
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the master/main branch
  push:
    branches: [ main ]

jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under test
      - uses: actions/checkout@v4
      #Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      #Run Tests
      - name: Run Tests
        run: mvn -B test
  # Build job
  build:
    # depends on test's job
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository
      - uses: actions/checkout@v4
      #Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      # Build the application using Maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
